### ISSUE TITLE
invalid byte sequence in UTF-8 (invalid argument)

### ISSUE THREAD

**Issue by Mozahler** [jpsim/SourceKitten#599]
I'm not a ruby programmer, so I don't think it's wise for me to muck around with sourcekitten.rb. I'm getting an error when running jazzy, and the compiler output points to sourcekitten. How can I find out which file has the invalid sequence/argument? StackOverflow has recommendations for replacing the invalid sequence:
`string.encode!('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '')`
 
and I can poke around with print statements to try to figure it out. But if it is getting an exception, I bet you'd like to know about it. I don't know whether it's one of my .swift files, or if it is an intermediate file or stream which is leading to the error.

/Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.9.6/lib/jazzy/sourcekitten.rb:30:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.9.6/lib/jazzy/sourcekitten.rb:30:in `autolink_block'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.9.6/lib/jazzy/sourcekitten.rb:733:in `autolink_text'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.9.6/lib/jazzy/sourcekitten.rb:797:in `autolink_document'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.9.6/lib/jazzy/doc_builder.rb:211:in `render'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.9.6/lib/jazzy/doc_builder.rb:224:in `document_markdown'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.9.6/lib/jazzy/doc_builder.rb:400:in `document'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.9.6/lib/jazzy/doc_builder.rb:90:in `block (2 levels) in build_docs'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.9.6/lib/jazzy/doc_builder.rb:89:in `open'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.9.6/lib/jazzy/doc_builder.rb:89:in `open'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.9.6/lib/jazzy/doc_builder.rb:89:in `block in build_docs'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.9.6/lib/jazzy/doc_builder.rb:100:in `block in each_doc'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.9.6/lib/jazzy/doc_builder.rb:96:in `each'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.9.6/lib/jazzy/doc_builder.rb:96:in `each_doc'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.9.6/lib/jazzy/doc_builder.rb:85:in `build_docs'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.9.6/lib/jazzy/doc_builder.rb:120:in `build_site'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.9.6/lib/jazzy/doc_builder.rb:156:in `build_docs_for_sourcekitten_output'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.9.6/lib/jazzy/doc_builder.rb:76:in `build'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.9.6/bin/jazzy:15:in `<top (required)>'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/bin/jazzy:22:in `load'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/bin/jazzy:22:in `<main>'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:24:in `eval'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:24:in `<main>'

I'm running Mojave (10.4.4) It's ruby 2.3.3 and Jazzy 0.9.6

How  do I add debug information? It's only about 40 swift files, so even a manual approach is doable. Any tips on what to look for would be appreciated. 
As always, thanks for your efforts!

**Comment by Mozahler** [comment]
I'm going to close this, as I don't see a way of recreating this issue. I started a new project, copied over the source code and everything works once again....
