### ISSUE TITLE
fatal error: module 'foobar' not found

### ISSUE THREAD

**Issue by rogerluan** [jpsim/SourceKitten#652]
Hey!

I'm having trouble running `sourcekitten doc` to generate Objective-C docs, and couldn't find any other users having this issue for some reason. I wonder if it has to do with the Xcode version.

### My command

(taken from https://github.com/realm/jazzy#mixed-objective-c--swift)

```
sourcekitten doc --objc $(pwd)/tellus-core/TellusCore.h \
      -- -x objective-c -isysroot $(xcrun --show-sdk-path --sdk iphonesimulator) \
      -I $(pwd) -fmodules > objcDoc.json
```

### Response:
```
/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/TellusCore.h:4:9: fatal error: module 'Realm' not found
Fatal error: Couldn't get category name: file /private/tmp/sourcekitten-20200116-76916-rox7z0/Source/SourceKittenFramework/Clang+SourceKitten.swift, line 127
[1]    85343 illegal hardware instruction  sourcekitten doc --objc $(pwd)/tellus-core/TellusCore.h -- -x objective-c   -
```

I tried moving things around but it throws this error the first time it encounters a 3rd party lib. I'm trying to generate docs for a Framework that has Cocoapods dependencies (such as Realm, as seen above).

## Env

macOS: 10.15.4 (19E287)
```
$ xcodebuild -version 
Xcode 11.4.1
Build version 11E503a
```

sourcekitten installed via brew today.

Any help will be highly appreciated! 🙏

**Comment by johnfairh** [comment]
The first error is the important one.  You'll need to pass header/framework search path flags to let `clang` (the C compiler) process the `@import Realm` or whatever in `TellusCore.h`.

**Comment by rogerluan** [comment]
@johnfairh do you mean `FRAMEWORK_SEARCH_PATHS`? Doesn't `sourcekitten doc` pick it up from my Xcode project settings file?

**Comment by rogerluan** [comment]
Is that the only info that it doesn't pick it up, or should I export all the properties from the xcode build settings into flags, and pass that along to `sourcekitten doc`? 🤔

**Comment by rogerluan** [comment]
> Is that the only info that it doesn't pick up, or should I export all the properties from the xcode build settings into flags, and pass that along to `sourcekitten doc`? 🤔

Nevermind, I found the answer to my own question here 👍   https://github.com/jpsim/SourceKitten/issues/88

I can't find a way to pass the FRAMEWORK_SEARCH_PATHS argument, though. Here's what I got so far:

```
local testing_argument="FRAMEWORK_SEARCH_PATHS=\"build/Debug-iphoneos/Realm\""
local xcodebuild_arguments="--objc,tellus-core/TellusCore.h,--,$testing_argument,-x,objective-c,-isysroot,$(xcrun --show-sdk-path),-I,$(pwd),-fmodules"
```

And I get the response:

```
warning: FRAMEWORK_SEARCH_PATHS="build/Debug-iphoneos/Realm": 'linker' input unused [-Wunused-command-line-argument]

tellus-core/TellusCore.h:4:9: fatal error: module 'Realm' not found
```

**Comment by rogerluan** [comment]
Following the comment here: https://github.com/realm/jazzy/issues/492#issuecomment-206517467

I tried:

```
bundle exec jazzy \
    --objc \
    --clean \
    --sdk iphonesimulator \
    --umbrella-header tellus-core/TellusCore.h \
    --build-tool-arguments $testing_argument \
    --framework-root tellus-core \
    --module-version 1.0.0 \
    --module tellus-core
```

But this is the response:
<details><summary>Click to expand</summary>
<p>

```
Unrecognized arguments: -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I
bundler: failed to load command: jazzy (/Users/rogerluan/Documents/Projects/tellus-core-ios/.vendor/ruby/2.6.0/bin/jazzy)
RuntimeError: /Users/rogerluan/Documents/Projects/tellus-core-ios/.vendor/ruby/2.6.0/gems/jazzy-0.13.1/bin/sourcekitten ["doc", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Vista.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Royal\\ Purple.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Denim.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Mandy.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Mine\\ Shaft.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Fuel\\ Yellow.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Scorpion.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Yellow\\ Orange.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Java.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Cerulean.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Cod\\ Gray.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Mercury.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Concrete.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Alabaster.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Tacao.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Heliotrope.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Brink\\ Pink.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/White\\ AF.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Chalky.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Shocking\\ Pink.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Boulder.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Alto.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Dallas.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Nobel.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Goldenrod.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Vivid\\ Violet.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets/Curious\\ Blue.colorset", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/Colors.xcassets", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/SAMKeychain.bundle/en.lproj", "-I", "/Users/rogerluan/Documents/Projects/tellus-core-ios/tellus-core/SAMKeychain.bundle", "FRAMEWORK_SEARCH_PATHS\\=\\\"build/Debug-iphoneos/Realm\\\""]

Unrecognized arguments: -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I

  /Users/rogerluan/Documents/Projects/tellus-core-ios/.vendor/ruby/2.6.0/gems/jazzy-0.13.1/lib/jazzy/executable.rb:36:in `execute_command'
  /Users/rogerluan/Documents/Projects/tellus-core-ios/.vendor/ruby/2.6.0/gems/jazzy-0.13.1/lib/jazzy/sourcekitten.rb:266:in `run_sourcekitten'
  /Users/rogerluan/Documents/Projects/tellus-core-ios/.vendor/ruby/2.6.0/gems/jazzy-0.13.1/lib/jazzy/doc_builder.rb:78:in `block in build'
  /Users/rogerluan/Documents/Projects/tellus-core-ios/.vendor/ruby/2.6.0/gems/jazzy-0.13.1/lib/jazzy/doc_builder.rb:76:in `chdir'
  /Users/rogerluan/Documents/Projects/tellus-core-ios/.vendor/ruby/2.6.0/gems/jazzy-0.13.1/lib/jazzy/doc_builder.rb:76:in `build'
  /Users/rogerluan/Documents/Projects/tellus-core-ios/.vendor/ruby/2.6.0/gems/jazzy-0.13.1/bin/jazzy:15:in `<top (required)>'
  /Users/rogerluan/Documents/Projects/tellus-core-ios/.vendor/ruby/2.6.0/bin/jazzy:23:in `load'
  /Users/rogerluan/Documents/Projects/tellus-core-ios/.vendor/ruby/2.6.0/bin/jazzy:23:in `<top (required)>'
```

</p>
</details>

**Comment by johnfairh** [comment]
You need to pass flags to sourcekitten for `clang`, the C compiler, so that it can compile the `TellusCore.h` file.  Xcode and its flags are not involved.  So `-F` for framework search paths, `-I` for include file search paths.

I don't know what your project structure is, you'll probably need to adjust this, but the form is probably something like:
```shell
sourcekitten doc --objc $(pwd)/tellus-core/TellusCore.h \
      -- -x objective-c -isysroot $(xcrun --show-sdk-path --sdk iphonesimulator) \
      -I $(pwd) -fmodules -F $(pwd)/build/Debug-iphoneos/Realm > objcDoc.json
```

**Comment by rogerluan** [comment]
Oh, got it! I missed that detail in your previous message, my bad! 
So, that worked! I passed all the framework search paths and generated the docs accordingly. The only problem I faced is that it also generated docs for the 3rd party frameworks headers, such as Realm. I think I can exclude that via jazzy, though, so not a big deal :) 

Thanks for the help @johnfairh ! 🙏
